name = "my-newspaper"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
main = ".vercel/output/static/_worker.js"
assets = { directory = ".vercel/output/static", binding = "ASSETS" }

[vars]
NEXT_PUBLIC_SUPABASE_URL = "https://tiryicmmbbwytdrxwnsb.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpcnlpY21tYmJ3eXRkcnh3bnNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc4MTUwMDcsImV4cCI6MjEwMzM5MTAwN30.9V3djlAZyjUx0FdlLuhDsMnEmtTH0JwYCwy6twT9QyY"
NEXT_PUBLIC_SITE_URL = "https://my-newspaper.notabeneinc.workers.dev"
NEXT_PUBLIC_CLOUDFLARE_TURNSTILE_SITE_KEY = "1x00000000000000000000AA"
